### ISSUE TITLE
API Server Docker not starting

### ISSUE THREAD

**Issue by ydennisy** [ClearGDPR/ClearGDPR#447]
**Describe the bug**
The API server is not running

**To Reproduce**
macosx High Sierra 10
Nodejs 9.8.0

Run `node setup.js` followed by `docker/run`

**Console Output**
```
➜  ClearGDPR git:(master) docker/run                                                      
Removing containers
No stopped containers
Removing containers
No stopped containers
Removing containers
No stopped containers
Removing containers
No stopped containers
Building demo-frontend
Step 1/12 : FROM node:8-alpine
 ---> e24de9a22ce3
Step 2/12 : LABEL maintainer="Clevertech DevOps <support@clevertech.biz>"
 ---> Using cache
 ---> c872ab70df68
Step 3/12 : RUN apk --no-cache add ca-certificates && update-ca-certificates
 ---> Using cache
 ---> c172f3a2bd72
Step 4/12 : RUN apk upgrade &&   apk add --no-cache git   make gcc g++ python
 ---> Using cache
 ---> e2dd42701f9f
Step 5/12 : EXPOSE 3000
 ---> Using cache
 ---> 6db6d90a2359
Step 6/12 : CMD ["npm", "start"]
 ---> Using cache
 ---> e32e6435f668
Step 7/12 : RUN mkdir -p /opt/app && mkdir /cache
 ---> Using cache
 ---> 4f028295aee3
Step 8/12 : WORKDIR /opt/app
 ---> Using cache
 ---> 5588c4806386
Step 9/12 : ADD package.json yarn.lock /cache/
 ---> Using cache
 ---> 843acb8f7a96
Step 10/12 : ADD .yarn-cache.tgz /
 ---> Using cache
 ---> 202a0028a820
Step 11/12 : RUN cd /cache   && yarn config set cache-folder /usr/local/share/.cache/yarn   && yarn   && cd /opt/app && ln -s /cache/node_modules node_modules   && tar czf /.yarn-cache.tgz /usr/local/share/.cache/yarn
 ---> Using cache
 ---> fe02d31f81c9
Step 12/12 : COPY . /opt/app
 ---> Using cache
 ---> 96178d6201c7
Successfully built 96178d6201c7
Successfully tagged cleargdpr/demo-frontend:latest
Building admin
Step 1/12 : FROM node:8-alpine
 ---> e24de9a22ce3
Step 2/12 : LABEL maintainer="Clevertech DevOps <support@clevertech.biz>"
 ---> Using cache
 ---> c872ab70df68
Step 3/12 : RUN apk --no-cache add ca-certificates && update-ca-certificates
 ---> Using cache
 ---> c172f3a2bd72
Step 4/12 : RUN apk upgrade &&   apk add --no-cache git   make gcc g++ python
 ---> Using cache
 ---> e2dd42701f9f
Step 5/12 : EXPOSE 4000
 ---> Using cache
 ---> c12c26432f17
Step 6/12 : CMD ["npm", "start"]
 ---> Using cache
 ---> 1816f97455ca
Step 7/12 : RUN mkdir -p /opt/app && mkdir /cache
 ---> Using cache
 ---> 36a90aec302f
Step 8/12 : WORKDIR /opt/app
 ---> Using cache
 ---> 61b09e307c90
Step 9/12 : ADD package.json yarn.lock /cache/
 ---> Using cache
 ---> f5555ffae7a8
Step 10/12 : ADD .yarn-cache.tgz /
 ---> Using cache
 ---> 25f89fce5074
Step 11/12 : RUN cd /cache   && yarn config set cache-folder /usr/local/share/.cache/yarn   && yarn   && cd /opt/app && ln -s /cache/node_modules node_modules   && tar czf /.yarn-cache.tgz /usr/local/share/.cache/yarn
 ---> Using cache
 ---> 6c146843cf98
Step 12/12 : COPY . /opt/app
 ---> Using cache
 ---> 08cc0493ca1d
Successfully built 08cc0493ca1d
Successfully tagged cleargdpr/admin:latest
Building db
Step 1/2 : FROM postgres
 ---> e3fc8fdbb39d
Step 2/2 : COPY db_setup.sh /docker-entrypoint-initdb.d/
 ---> Using cache
 ---> 219e04e98ba0
Successfully built 219e04e98ba0
Successfully tagged cleargdpr/postgres:latest
Building cg_processor
Step 1/13 : FROM node:8-alpine
 ---> e24de9a22ce3
Step 2/13 : LABEL maintainer="Clevertech DevOps <support@clevertech.biz>"
 ---> Using cache
 ---> c872ab70df68
Step 3/13 : RUN apk --no-cache add ca-certificates && update-ca-certificates
 ---> Using cache
 ---> c172f3a2bd72
Step 4/13 : RUN apk upgrade &&     apk add --no-cache git       make gcc g++ python
 ---> Using cache
 ---> 00fab8d7c538
Step 5/13 : EXPOSE 3000
 ---> Using cache
 ---> 2ac530db6518
Step 6/13 : CMD ["yarn", "run", "start"]
 ---> Using cache
 ---> a0cf26c0be4e
Step 7/13 : RUN mkdir -p /opt/app && mkdir /cache
 ---> Using cache
 ---> a8d4ec384c03
Step 8/13 : WORKDIR /opt/app
 ---> Using cache
 ---> 8ada42d0751a
Step 9/13 : ADD package.json yarn.lock /cache/
 ---> Using cache
 ---> e1bb802e5d58
Step 10/13 : ADD .yarn-cache.tgz /
 ---> Using cache
 ---> 550a81b42061
Step 11/13 : RUN cd /cache   && yarn config set cache-folder /usr/local/share/.cache/yarn   && yarn   && cd /opt/app && ln -s /cache/node_modules node_modules   && tar czf /.yarn-cache.tgz /usr/local/share/.cache/yarn
 ---> Running in 0b6fca15fe50
yarn config v1.6.0
success Set "cache-folder" to "/usr/local/share/.cache/yarn".
Done in 0.08s.
yarn install v1.6.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 164.06s.
tar: removing leading '/' from member names
Removing intermediate container 0b6fca15fe50
 ---> d2718f4ca585
Step 12/13 : RUN apk del make gcc g++ python
 ---> Running in 0778e47a93c9
WARNING: Ignoring APKINDEX.84815163.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.24d64ab1.tar.gz: No such file or directory
(1/23) Purging g++ (6.3.0-r4)
(2/23) Purging gcc (6.3.0-r4)
(3/23) Purging binutils (2.30-r1)
(4/23) Purging libatomic (6.3.0-r4)
(5/23) Purging libgomp (6.3.0-r4)
(6/23) Purging libc-dev (0.7.1-r0)
(7/23) Purging musl-dev (1.1.16-r14)
(8/23) Purging make (4.2.1-r0)
(9/23) Purging python2 (2.7.15-r0)
(10/23) Purging binutils-libs (2.30-r1)
(11/23) Purging mpc1 (1.0.3-r0)
(12/23) Purging mpfr3 (3.1.5-r0)
(13/23) Purging isl (0.17.1-r0)
(14/23) Purging gmp (6.1.2-r0)
(15/23) Purging pkgconf (1.3.7-r0)
(16/23) Purging libbz2 (1.0.6-r5)
(17/23) Purging libffi (3.2.1-r3)
(18/23) Purging gdbm (1.12-r0)
(19/23) Purging readline (6.3.008-r5)
(20/23) Purging ncurses-libs (6.0_p20171125-r1)
(21/23) Purging ncurses-terminfo (6.0_p20171125-r1)
(22/23) Purging ncurses-terminfo-base (6.0_p20171125-r1)
(23/23) Purging sqlite-libs (3.20.1-r2)
Executing busybox-1.26.2-r11.trigger
OK: 27 MiB in 21 packages
Removing intermediate container 0778e47a93c9
 ---> 4d3ccaadf4fc
Step 13/13 : COPY . /opt/app
 ---> 020cfc8f370b
Successfully built 020cfc8f370b
Successfully tagged cleargdpr/cg:latest
Building cg
Step 1/13 : FROM node:8-alpine
 ---> e24de9a22ce3
Step 2/13 : LABEL maintainer="Clevertech DevOps <support@clevertech.biz>"
 ---> Using cache
 ---> c872ab70df68
Step 3/13 : RUN apk --no-cache add ca-certificates && update-ca-certificates
 ---> Using cache
 ---> c172f3a2bd72
Step 4/13 : RUN apk upgrade &&     apk add --no-cache git       make gcc g++ python
 ---> Using cache
 ---> 00fab8d7c538
Step 5/13 : EXPOSE 3000
 ---> Using cache
 ---> 2ac530db6518
Step 6/13 : CMD ["yarn", "run", "start"]
 ---> Using cache
 ---> a0cf26c0be4e
Step 7/13 : RUN mkdir -p /opt/app && mkdir /cache
 ---> Using cache
 ---> a8d4ec384c03
Step 8/13 : WORKDIR /opt/app
 ---> Using cache
 ---> 8ada42d0751a
Step 9/13 : ADD package.json yarn.lock /cache/
 ---> Using cache
 ---> e1bb802e5d58
Step 10/13 : ADD .yarn-cache.tgz /
 ---> Using cache
 ---> 550a81b42061
Step 11/13 : RUN cd /cache   && yarn config set cache-folder /usr/local/share/.cache/yarn   && yarn   && cd /opt/app && ln -s /cache/node_modules node_modules   && tar czf /.yarn-cache.tgz /usr/local/share/.cache/yarn
 ---> Using cache
 ---> d2718f4ca585
Step 12/13 : RUN apk del make gcc g++ python
 ---> Using cache
 ---> 4d3ccaadf4fc
Step 13/13 : COPY . /opt/app
 ---> Using cache
 ---> 020cfc8f370b
Successfully built 020cfc8f370b
Successfully tagged cleargdpr/cg:latest
Building demo-api
Step 1/11 : FROM node:8-alpine
 ---> e24de9a22ce3
Step 2/11 : LABEL maintainer="Clevertech DevOps <support@clevertech.biz>"
 ---> Using cache
 ---> c872ab70df68
Step 3/11 : RUN apk --no-cache add ca-certificates && update-ca-certificates
 ---> Using cache
 ---> c172f3a2bd72
Step 4/11 : EXPOSE 3000
 ---> Running in eaec1e072ac0
Removing intermediate container eaec1e072ac0
 ---> 99509402aaea
Step 5/11 : CMD ["yarn", "run", "start"]
 ---> Running in 5275af752835
Removing intermediate container 5275af752835
 ---> 046304572f9d
Step 6/11 : RUN mkdir -p /opt/app && mkdir /cache
 ---> Running in 2cc711a4751f
Removing intermediate container 2cc711a4751f
 ---> 012d184b0b0c
Step 7/11 : WORKDIR /opt/app
Removing intermediate container 66ba04d75bf7
 ---> 3c023714a6c1
Step 8/11 : ADD package.json yarn.lock /cache/
 ---> 402a427574e7
Step 9/11 : ADD .yarn-cache.tgz /
 ---> 5fa2faebe6eb
Step 10/11 : RUN cd /cache   && yarn config set cache-folder /usr/local/share/.cache/yarn   && yarn   && cd /opt/app && ln -s /cache/node_modules node_modules   && tar czf /.yarn-cache.tgz /usr/local/share/.cache/yarn
 ---> Running in 7be4653bbfc8
yarn config v1.6.0
success Set "cache-folder" to "/usr/local/share/.cache/yarn".
Done in 0.07s.
yarn install v1.6.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 18.82s.
tar: removing leading '/' from member names
Removing intermediate container 7be4653bbfc8
 ---> c977ae7782b2
Step 11/11 : COPY . /opt/app
 ---> 5d7c9e8afef9
Successfully built 5d7c9e8afef9
Successfully tagged cleargdpr/demo-api:latest
adminer uses an image, skipping
constellation1 uses an image, skipping
constellation2 uses an image, skipping
geth1 uses an image, skipping
geth2 uses an image, skipping
Checking if I need to retrieve Yarn cache and lock file for cg
Not retrieving
Done
Checking if I need to retrieve Yarn cache and lock file for admin
Not retrieving
Done
Checking if I need to retrieve Yarn cache and lock file for demo-api
Not retrieving
Done
Checking if I need to retrieve Yarn cache and lock file for demo-frontend
Not retrieving
Done
Creating network "cleargdpr_default" with the default driver
Creating network "cleargdpr_quorum_net" with driver "bridge"
Creating volume "cleargdpr_db_data" with default driver
Creating volume "cleargdpr_quorum_data1" with default driver
Creating volume "cleargdpr_quorum_data2" with default driver
Pulling adminer (adminer:)...
latest: Pulling from library/adminer
8e3ba11ec2a2: Pull complete
a4c1ef410e64: Pull complete
fc1230cd877c: Pull complete
4732b87605ad: Pull complete
d5e391ea991b: Pull complete
549ad71b9a98: Pull complete
4e5fc7f5fd0b: Pull complete
5bf6021b9316: Pull complete
3a090c506ff6: Pull complete
81c1f347c0eb: Pull complete
67647183428f: Pull complete
ae0064119944: Pull complete
1c34d1db093d: Pull complete
1c53bace8a06: Pull complete
fd62e8eb1a25: Pull complete
85db932a763c: Pull complete
Digest: sha256:a269ef230dc9f4f5f19468d038a9e66dd7095117310cfcf3ce2157266910b639
Status: Downloaded newer image for adminer:latest
Pulling constellation1 (cleargdpr/quorum:latest)...
latest: Pulling from cleargdpr/quorum
3b37166ec614: Pull complete
ba077e1ddb3a: Pull complete
34c83d2bc656: Pull complete
84b69b6e4743: Pull complete
0f72e97e1f61: Pull complete
23576d4b3ca5: Pull complete
1f2b7f77cdcd: Pull complete
2b5d7cbb01d4: Pull complete
acf5cf3bbf90: Pull complete
59ef3118af69: Pull complete
Digest: sha256:8bf0a6aad6c826dd2462733eff6a7081b68cbf47dfb0e451b3400a0d6ed02027
Status: Downloaded newer image for cleargdpr/quorum:latest
Pulling constellation2 (cleargdpr/quorum_processor:0.0.2)...
0.0.2: Pulling from cleargdpr/quorum_processor
8ee29e426c26: Pull complete
6e83b260b73b: Pull complete
e26b65fd1143: Pull complete
40dca07f8222: Pull complete
b420ae9e10b3: Pull complete
5fc76a66d50c: Pull complete
65237f249abd: Pull complete
9db23e8184cb: Pull complete
7f5f83c97da7: Pull complete
1e5cf63137d6: Pull complete
Digest: sha256:98baf67e9a864c4511346f3349aa67e0714d23b918339c19e106c2e86cb2aebe
Status: Downloaded newer image for cleargdpr/quorum_processor:0.0.2
Creating cleargdpr_adminer_1        ... done
Creating cleargdpr_constellation1_1 ... done
Creating cleargdpr_admin_1          ... done
Creating cleargdpr_constellation2_1 ... done
Creating cleargdpr_demo-frontend_1  ... done
Creating cleargdpr_db_1             ... done
Creating cleargdpr_cg_processor_1   ... done
Creating cleargdpr_cg_1             ... done
Creating cleargdpr_geth2_1          ... done
Creating cleargdpr_geth1_1          ... done
Creating cleargdpr_demo-api_1       ... done
Attaching to cleargdpr_db_1, cleargdpr_constellation2_1, cleargdpr_adminer_1, cleargdpr_constellation1_1, cleargdpr_geth1_1, cleargdpr_geth2_1, cleargdpr_cg_1, cleargdpr_cg_processor_1, cleargdpr_demo-frontend_1, cleargdpr_admin_1, cleargdpr_demo-api_1
db_1              | The files belonging to this database system will be owned by user "postgres".
db_1              | This user must also own the server process.
db_1              | 
db_1              | The database cluster will be initialized with locale "en_US.utf8".
db_1              | The default database encoding has accordingly been set to "UTF8".
db_1              | The default text search configuration will be set to "english".
db_1              | 
db_1              | Data page checksums are disabled.
db_1              | 
db_1              | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1              | creating subdirectories ... ok
constellation2_1  | [*] Setup configuration for Constellation
db_1              | selecting default max_connections ... 100
db_1              | selecting default shared_buffers ... 128MB
db_1              | selecting dynamic shared memory implementation ... posix
constellation2_1  | /scripts/start_node_processor.sh: line 19: NODE_IP: unbound variable
constellation2_1  | /scripts/start_node_processor.sh: line 20: NODE_PORT: unbound variable
constellation2_1  | /scripts/start_node_processor.sh: line 21: OTHER_NODE_URLS: unbound variable
db_1              | creating configuration files ... ok
adminer_1         | PHP 7.2.9 Development Server started at Wed Sep  5 11:03:45 2018
constellation1_1  | [*] Setup configuration for Constellation
db_1              | running bootstrap script ... ok
geth1_1           | [*] Setup configuration for Geth
geth1_1           | /scripts/start_node.sh: line 42: NODE_KEY: unbound variable
constellation1_1  | /scripts/start_node.sh: line 21: OTHER_NODE_URLS: unbound variable
constellation1_1  | /scripts/start_node.sh: line 20: NODE_PORT: unbound variable
constellation1_1  | /scripts/start_node.sh: line 19: NODE_IP: unbound variable
cg_1              | yarn run v1.6.0
cg_1              | $ bnr start-dev
cg_1              | running better-npm-run in /opt/app
db_1              | performing post-bootstrap initialization ... ok
cleargdpr_constellation2_1 exited with code 1
geth2_1           | /scripts/start_node_processor.sh: line 42: NODE_KEY: unbound variable
cg_1              | Executing script: start-dev
cg_1              | 
geth2_1           | [*] Setup configuration for Geth
cg_1              | to be executed: node src/wait-for-db.js && knex migrate:latest && nodemon --inspect=0.0.0.0:9230 
cg_1              | /opt/app/node_modules/knex/lib/client.js:108
cg_1              |     throw new Error('knex: Required configuration option \'client\' is missing.');
cg_1              |     ^
db_1              | syncing data to disk ... ok
db_1              | 
db_1              | Success. You can now start the database server using:
db_1              | 
db_1              |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1              | 
cg_1              | 
cg_1              | Error: knex: Required configuration option 'client' is missing.
cg_1              |     at new Client (/opt/app/node_modules/knex/lib/client.js:108:11)
cg_1              |     at Knex (/opt/app/node_modules/knex/lib/index.js:60:34)
cg_1              |     at Object.<anonymous> (/opt/app/src/wait-for-db.js:3:27)
cg_1              |     at Module._compile (module.js:652:30)
cg_1              |     at Object.Module._extensions..js (module.js:663:10)
cg_1              |     at Module.load (module.js:565:32)
cg_1              |     at tryModuleLoad (module.js:505:12)
cg_1              |     at Function.Module._load (module.js:497:3)
cg_1              |     at Function.Module.runMain (module.js:693:10)
cg_1              |     at startup (bootstrap_node.js:191:16)
cleargdpr_geth1_1 exited with code 1
db_1              | 
db_1              | WARNING: enabling "trust" authentication for local connections
db_1              | You can change this by editing pg_hba.conf or using the option -A, or
db_1              | --auth-local and --auth-host, the next time you run initdb.
demo-frontend_1   | 
demo-frontend_1   | > @cleargdpr/demo-frontend@1.0.0 start /opt/app
demo-frontend_1   | > node scripts/start.js
demo-frontend_1   | 
cg_processor_1    | yarn run v1.6.0
db_1              | ****************************************************
db_1              | WARNING: No password has been set for the database.
db_1              |          This will allow anyone with access to the
db_1              |          Postgres port to access your database. In
db_1              |          Docker's default configuration, this is
db_1              |          effectively any other container on the same
db_1              |          system.
db_1              | 
db_1              |          Use "-e POSTGRES_PASSWORD=password" to set
db_1              |          it in "docker run".
db_1              | ****************************************************
admin_1           | yarn run v1.6.0
admin_1           | $ node scripts/start.js
cg_1              |     at bootstrap_node.js:612:3
cg_processor_1    | $ bnr start-dev
admin_1           | Starting the development server...
admin_1           | 
db_1              | waiting for server to start....2018-09-05 11:03:48.811 UTC [40] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
cg_processor_1    | running better-npm-run in /opt/app
db_1              | 2018-09-05 11:03:48.831 UTC [41] LOG:  database system was shut down at 2018-09-05 11:03:47 UTC
db_1              | 2018-09-05 11:03:48.838 UTC [40] LOG:  database system is ready to accept connections
cleargdpr_constellation1_1 exited with code 1
cg_1              | error Command failed with exit code 1.
db_1              |  done
db_1              | server started
cleargdpr_geth2_1 exited with code 1
db_1              | CREATE DATABASE
db_1              | 
cg_processor_1    | Executing script: start-dev
cg_processor_1    | 
cg_processor_1    | to be executed: node src/wait-for-db.js && knex migrate:latest && nodemon --inspect=0.0.0.0:9230 
cg_1              | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
cg_processor_1    | /opt/app/node_modules/knex/lib/client.js:108
cg_processor_1    |     throw new Error('knex: Required configuration option \'client\' is missing.');
cg_processor_1    |     ^
cg_processor_1    | 
cg_processor_1    | Error: knex: Required configuration option 'client' is missing.
cg_processor_1    |     at new Client (/opt/app/node_modules/knex/lib/client.js:108:11)
cg_processor_1    |     at Knex (/opt/app/node_modules/knex/lib/index.js:60:34)
cg_processor_1    |     at Object.<anonymous> (/opt/app/src/wait-for-db.js:3:27)
cg_processor_1    |     at Module._compile (module.js:652:30)
cg_processor_1    |     at Object.Module._extensions..js (module.js:663:10)
cg_processor_1    |     at Module.load (module.js:565:32)
cg_processor_1    |     at tryModuleLoad (module.js:505:12)
cg_processor_1    |     at Function.Module._load (module.js:497:3)
cg_processor_1    |     at Function.Module.runMain (module.js:693:10)
cg_processor_1    |     at startup (bootstrap_node.js:191:16)
cg_processor_1    |     at bootstrap_node.js:612:3
db_1              | CREATE ROLE
db_1              | 
db_1              | 
db_1              | /usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/db_setup.sh
db_1              | 
cg_processor_1    | error Command failed with exit code 1.
cg_processor_1    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
db_1              | CREATE DATABASE
db_1              | CREATE DATABASE
db_1              | 
db_1              | 2018-09-05 11:03:50.767 UTC [40] LOG:  received fast shutdown request
db_1              | waiting for server to shut down....2018-09-05 11:03:50.771 UTC [40] LOG:  aborting any active transactions
db_1              | 2018-09-05 11:03:50.774 UTC [40] LOG:  worker process: logical replication launcher (PID 47) exited with exit code 1
db_1              | 2018-09-05 11:03:50.778 UTC [42] LOG:  shutting down
db_1              | 2018-09-05 11:03:50.808 UTC [40] LOG:  database system is shut down
db_1              |  done
db_1              | server stopped
db_1              | 
db_1              | PostgreSQL init process complete; ready for start up.
db_1              | 
db_1              | 2018-09-05 11:03:50.907 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1              | 2018-09-05 11:03:50.907 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1              | 2018-09-05 11:03:50.916 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1              | 2018-09-05 11:03:50.983 UTC [76] LOG:  database system was shut down at 2018-09-05 11:03:50 UTC
db_1              | 2018-09-05 11:03:50.990 UTC [1] LOG:  database system is ready to accept connections
cleargdpr_cg_1 exited with code 1
cleargdpr_cg_processor_1 exited with code 1
demo-api_1        | yarn run v1.6.0
demo-api_1        | $ bnr start-dev
demo-api_1        | running better-npm-run in /opt/app
demo-api_1        | Executing script: start-dev
demo-api_1        | 
demo-api_1        | to be executed: node src/wait-for-db.js && knex migrate:latest && nodemon --inspect=0.0.0.0:9229 
demo-frontend_1   | Starting the development server...
demo-frontend_1   | 
demo-api_1        | /opt/app/node_modules/knex/lib/client.js:108
demo-api_1        |     throw new Error('knex: Required configuration option \'client\' is missing.');
demo-api_1        |     ^
demo-api_1        | 
demo-api_1        | Error: knex: Required configuration option 'client' is missing.
demo-api_1        |     at new Client (/opt/app/node_modules/knex/lib/client.js:108:11)
demo-api_1        |     at Knex (/opt/app/node_modules/knex/lib/index.js:60:34)
demo-api_1        |     at Object.<anonymous> (/opt/app/src/wait-for-db.js:2:27)
demo-api_1        |     at Module._compile (module.js:652:30)
demo-api_1        |     at Object.Module._extensions..js (module.js:663:10)
demo-api_1        |     at Module.load (module.js:565:32)
demo-api_1        |     at tryModuleLoad (module.js:505:12)
demo-api_1        |     at Function.Module._load (module.js:497:3)
demo-api_1        |     at Function.Module.runMain (module.js:693:10)
demo-api_1        |     at startup (bootstrap_node.js:191:16)
demo-api_1        |     at bootstrap_node.js:612:3
demo-api_1        | error Command failed with exit code 1.
demo-api_1        | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
cleargdpr_demo-api_1 exited with code 1
demo-frontend_1   | Compiled successfully!
demo-frontend_1   | 
demo-frontend_1   | You can now view @cleargdpr/demo-frontend in the browser.
demo-frontend_1   | 
demo-frontend_1   |   Local:            http://localhost:3000/
demo-frontend_1   |   On Your Network:  http://172.20.0.6:3000/
demo-frontend_1   | 
demo-frontend_1   | Note that the development build is not optimized.
demo-frontend_1   | To create a production build, use yarn build.
demo-frontend_1   | 
admin_1           | Compiled successfully!
admin_1           | 
admin_1           | You can now view @cleargdpr/admin in the browser.
admin_1           | 
admin_1           |   Local:            http://localhost:4000/
admin_1           |   On Your Network:  http://172.20.0.7:4000/
admin_1           | 
admin_1           | Note that the development build is not optimized.
admin_1           | To create a production build, use yarn build.
admin_1           | 

```

**Comment by sindelio** [comment]
The knex configuration for the database seems to be missing

**Comment by sindelio** [comment]
Inside the root folder of the project, try this:

```docker-compose down -v``` - Stops and removes the containers, volumes and networks associated with a docker-compose file

Then:

```node setup.js``` - Run the setup again, this will create the environment for you.

Then:

```docker/run``` Restart the containers

Please let us know the results
